### ISSUE TITLE
Suggestion: Provide default configuration for sourcekit-lsp.serverPath on macOS

### ISSUE THREAD

**Issue by Feuermurmel** [vknabel/vscode-swift-development-environment#106]
On macOS `sourcekit-lsp` can be run using `xcrun sourcekit-lsp`, which works regardless of which Xcode version is installed. I.e. `/usr/bin/xcrun sourcekit-lsp` could be used as the default value for `sourcekit-lsp.serverPath`. (it does not work right now, but it could be made to work). This would make using setting up SDE on macOS a bit quicker for new users.

**Comment by vknabel** [comment]
It's a great suggestion. I didn't find enough time to implement it.
PRs welcome.
