### ISSUE TITLE
Extension not available in Open VSX Registry

### ISSUE THREAD

**Issue by segabor** [vknabel/vscode-swift-development-environment#118]
Today I switched over to [vscodium](https://vscodium.com) but the extension was not not listed in the [Open VSX Registry](https://open-vsx.org), an open alternative to VSCode Marketplace.

I made the extension work by manually copying it from the existing `.vscode/extensions` folder under `.vscode-oss`.

**Comment by segabor** [comment]
I just learned that vscodium uses [Open VSX Registry](https://open-vsx.org/?search=swift&category=&sortBy=relevance&sortOrder=desc) to provide extensions for vscodium.

**Comment by vknabel** [comment]
@segabor good news!
I just [released](https://open-vsx.org/?search=vknabel&category=&sortBy=relevance&sortOrder=desc) my actively maintained vscode extensions.

**Comment by segabor** [comment]
Awesome! Thank you.
