### ISSUE TITLE
Description and settings disagree on default engine

### ISSUE THREAD

**Issue by CodingMarkus** [vknabel/vscode-swift-development-environment#125]
According to description, `sourcekit-lsp` is default:

![Screenshot 2024-04-11 at 14 00 51](https://github.com/vknabel/vscode-swift-development-environment/assets/26418089/a17229cc-344a-4818-8035-94080f3fdb96)

But it isn't! `sourcekite` is default:

![Screenshot 2024-04-11 at 14 01 54](https://github.com/vknabel/vscode-swift-development-environment/assets/26418089/c65de9fc-00a1-4d23-8ab4-06ab61ea207f)

**Comment by vknabel** [comment]
Hi, thanks for opening an issue. But I decided to archive this repository as today there is no good reason to actually use this extension anymore. Please use the official swift extension from apple.
