### ISSUE TITLE
Go to definition not working

### ISSUE THREAD

**Issue by LinusU** [vknabel/vscode-swift-development-environment#14]
<img width="446" alt="screen shot 2018-04-18 at 12 06 24" src="https://user-images.githubusercontent.com/189580/38928490-eed96fd6-4300-11e8-9dc1-3e6cb3a3e8f7.png">

Getting this message when trying to right click and chose "Go to definition". The class is defined in another file in the same project. I have also tried it with classes defined in the same file, same error.

**Comment by vknabel** [comment]
@LinusU did you use any import statements, that you don't get any completions or hovers for?
In that case this may be related to another issue, where sourcekit does not emit type information for (some) imports.

**Comment by LinusU** [comment]
Nothing other than UIKit, the file was simply another file in the same project. Oh, I should probably have mentioned, this is not a SPM project, but an Xcode one, maybe that's the culprint?

**Comment by vknabel** [comment]
I have fixed the problem I meant, but your problem seems to be a different one.

There were two issues:
1. Imports were not working correctly. (Mostly affected SPM)
2. Your issue. (Probably: your swift files are not indexed together)

**Comment by LinusU** [comment]
Awesome as always! Thank you ❤️

**Comment by LinusU** [comment]
> Will no longer write sde.buildOnSave or editor.quickSuggestions to workspace settings

🙏 🙏 🙏 🙏

**Comment by vknabel** [comment]
Released as [2.3.1](https://github.com/vknabel/vscode-swift-development-environment/releases/tag/2.3.1).
Will now scan the repo for swift files on startup.
