### ISSUE TITLE
Can't get autocomplete for WatchOS to work

### ISSUE THREAD

**Issue by antgly** [vknabel/vscode-swift-development-environment#15]
Adding "armv7k-apple-watchos4.3" to the workspace setting options as a target doesn't seem to allow autocompletion for WatchKit. Tried it with "armv7k-apple-watchos4" and "armv7k-apple-watchos4.0" as well. I've also tried it with the Swift.org Swift 4.3 toolchain and the built-in Xcode one. UIKit autocompletion for iOS works fine though.

**Comment by vknabel** [comment]
Released as [2.3.1](https://github.com/vknabel/vscode-swift-development-environment/releases/tag/2.3.1)
