### ISSUE TITLE
Wrong color for parameter named "continue"

### ISSUE THREAD

**Issue by LinusU** [vknabel/vscode-swift-development-environment#16]
<img width="381" alt="screen shot 2018-04-20 at 11 35 51" src="https://user-images.githubusercontent.com/189580/39046755-2f70be34-448f-11e8-8491-4723a325ae94.png">

Pasted in the following:

```swift
optional func application(_ application: UIApplication, 
                 continue userActivity: NSUserActivity, 
       restorationHandler: @escaping ([Any]?) -> Void) -> Bool
```

and started googling what the `continue` keyword meant for a function parameter 😂

**Comment by vknabel** [comment]
The syntax highlighting itself comes from vscode and is built in.
It even worked on a linux VM without swift or this extension installed.

But I don't know where you need to open the issue.
Maybe they use [textmate/swift.tmbundle](https://github.com/textmate/swift.tmbundle)?

**Comment by LinusU** [comment]
Let's try 😀

**Comment by LinusU** [comment]
textmate/swift.tmbundle#34
