### ISSUE TITLE
Doesn't recognize Operation from Foundation - only recognizes NSOperation

### ISSUE THREAD

**Issue by antgly** [vknabel/vscode-swift-development-environment#17]
I've even set a compiler flag for Swift 4.1 and I'm still not getting Operation recognized as a valid class.

**Comment by vknabel** [comment]
Thanks for filing an issue!
Do you mean the fact that `NSOperation` is colorized but `Operation` not?
Syntax highlighting is not handled by this extension and is part of vscode itself. More details [here](https://github.com/textmate/swift.tmbundle/issues/34#issuecomment-383435383). 

Just in case you meant autocompletion: the extension warns about using `NSOperation` as it has been deprecated. In that case SDE would use the wrong swift installation and version. You would need to set the swift driver path within your vscode settings to point to swift 4.x.

**Comment by antgly** [comment]
That might be the case upsettingly. Haven't delved into it too much but my Swift compiler vscode extension settings didn't do me any good.

**Comment by vknabel** [comment]
Closing in favor of https://github.com/vknabel/All-in-One-Swift-for-vscode/issues/4
