### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by sbromberger** [vknabel/vscode-swift-development-environment#20]
Not sure whether this is related to this plugin, but I'm getting ` expressions are not allowed at the top level` errors from a brand new library creation (via `swift package init --type=library`). The only content is boilerplate:
```
struct Rationals {
    var text = "Hello, World!"
}
```

Any ideas on what the problem might be?

**Comment by sbromberger** [comment]
Fixed - but not quite sure how.

**Comment by vknabel** [comment]
This behavior sounds weird. If this this happens again, you can reopen this issue and I will have a deeper look.
