### ISSUE TITLE
Build problems win CLI Swift app

### ISSUE THREAD

**Issue by carlca** [vknabel/vscode-swift-development-environment#28]
```
macOS 10.13.6
Swift 4.1.2
VSCode Version 1.25.0-insider (1.25.0-insider)
MSDE 2.4.3
```
Hello, I have setup my system following this guide https://forums.swift.org/t/vscode-settings-for-swift/12216 and as you can see it include MSDE. 

I'm trying to debug a simple CLI Swift app which has the usual Swift folder structure. When I hit the green run button, the first thing I see is this message...

![screen shot 2018-06-22 at 22 29 30](https://user-images.githubusercontent.com/260612/41800528-de7259a0-766d-11e8-8678-88c47a0aac77.png)

If I select the "Show Errors" option, I see this message...
 
![screen shot 2018-06-22 at 22 31 47](https://user-images.githubusercontent.com/260612/41800149-2fb96a8a-766c-11e8-8a76-205997f8a1e5.png)

If I select "Debug Anyway", I see these messages...

![screen shot 2018-06-22 at 22 34 28](https://user-images.githubusercontent.com/260612/41800210-80c719a4-766c-11e8-88bf-f6641a676282.png)

and

![screen shot 2018-06-22 at 22 35 35](https://user-images.githubusercontent.com/260612/41800235-a1464e02-766c-11e8-8989-d841f7cb3c1e.png)

Either way, I don't seem to be able to debug my program.

This is my `launch.json`...

```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "lldb",
            "request": "launch",
            "preLaunchTask": "swiftc with debug",
            "name": "Debug",
            "program": "${fileDirname}/${fileBasenameNoExtension}",
            "args": [],
            "sourceLanguages": [
                "swift"
            ]
        }
    ]
}
```

This is my `tasks.json`...

```json
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "swiftc with debug",
            "type": "shell",
            "command": "swiftc -g ${file}",
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "presentation": {
                "panel": "dedicated"
            }
        }
    ]
}
```

Both config files were as suggested by the https://forums.swift.org/t/vscode-settings-for-swift/12216 page.

Thanks in advance for any help you can give me.

Cheers,
Carl

**Comment by vknabel** [comment]
> On the MSDE plugin repo at Github, there appear to be two alternative macOS installation options for installing sourcekite. One is described as when using swiftenv or multiple Toolchains while the other is described as using Xcode's Toolchain.
>
> Which one should I use? I suspect it's the latter option but I would like to be sure!

If you do not regular switch between different swift versions, picking the latter option was correct!

**Comment by carlca** [comment]
Thanks, Valentin! With your help, I've now got syntax-highlighting, program execution and debugging all working in VSCode. Yay! Congratulations on your victory against Sweden, by the way, but you left it a bit late, didn't you 😉

**Comment by vknabel** [comment]
Happy to help 👍

> Congratulations on your victory against Sweden, by the way, but you left it a bit late, didn't you.

Thanks. The best comment on the game: https://twitter.com/GaryLineker/status/1010612676530196480
> Football is a simple game, 22 men chase the ball for 82 minutes and the Germans get a player sent off so 21 men chase the ball for 13 minutes and at the end the Germans somehow fucking win.
