### ISSUE TITLE
Configured debug type 'lldb' is not supported.

### ISSUE THREAD

**Issue by troyibm** [vknabel/vscode-swift-development-environment#29]
I've followed the instructions on https://marketplace.visualstudio.com/items?itemName=vknabel.vscode-swift-development-environment#overview

One that I think is wrong with the doc is the comments on the launch.json file..

![image](https://user-images.githubusercontent.com/19195331/41813264-25f80330-76f8-11e8-8484-b7d721f07f7b.png)

the `launch.json` and `tasks.json` go in a `.vscode/` directory, not `.vscode.json/` directory.

But I'm able to get autocomplete working with sourcekit and all, but when I try to do the "Run your Executable" configuration, I get the error `Configured debug type 'lldb' is not supported.`

![image](https://user-images.githubusercontent.com/19195331/41813285-6ecd3d82-76f8-11e8-82c2-3628716bd94a.png)

**Comment by troyibm** [comment]
I've quit VSCode and restarted and that doesn't fix the problem.

**Comment by troyibm** [comment]
Doh.. I missed that we need to install the CodeLLDB extension too.

![image](https://user-images.githubusercontent.com/19195331/41813588-4d92c870-76fe-11e8-900b-bca404753ccd.png)

Never mind...
and thanks for taking over this project.  I hate Xcode cause it doesn't have a vi keybindings built-in.

**Comment by vknabel** [comment]
Hi. Thanks for opening the issue. 

> the launch.json and tasks.json go in a .vscode/ directory, not .vscode.json/ directory.

Thanks. I just updated the readme.

> Doh.. I missed that we need to install the CodeLLDB extension too.

Great to head :)
