### ISSUE TITLE
Swift 4 compatibility?

### ISSUE THREAD

**Issue by thomas-alrek** [vknabel/vscode-swift-development-environment#3]
I just got the extension setup, and configured SDE correct.
However, I don't get any autocompletion, or syntax error highlightning.

I have Swift 4.0.2. Is it not compatible?

**Comment by vknabel** [comment]
@thomas-alrek Thank you for your feedback. 
I assume you are using SDE in version 2.1.0. If you don't you are probably still using the outdated version this project is based on ([jinmingjian/sde](https://github.com/jinmingjian/sde)), which does not support Swift 4.

In any other case: which OS are you using? 
Are you using Xcode's builtin Swift version or did you install one by yourself?
What kind of project are you using? If it is open source, I could try it on my own machine.

**Comment by thomas-alrek** [comment]
Thanks for the reply.

I am running on macOS 10.13, and have installed Swift 4.0.2 (Apple Swift version 4.0.2 (swiftlang-900.0.69.2 clang-900.0.38)) through XCode.

I have compiled SDE myself, and configured VScode to point to the compiled binary.

I am not working on any specific project, just testing it out. I get syntax highlighting, but no IntelliSense.

**Comment by vknabel** [comment]
@thomas-alrek After restarting my vscode, I could reproduce your issue. I am going to fix this tomorrow.

**Comment by vknabel** [comment]
@thomas-alrek Sorry for the delay. Today's release `2.1.1` should fix this issue.
Can you confirm this?
