### ISSUE TITLE
Can't run the extension: "Starting client failed"

### ISSUE THREAD

**Issue by VojtaStavik** [vknabel/vscode-swift-development-environment#31]
#### What I did:
- I installed the extension version `2.4.3.`
- I built `sourcekite` as described in the readme
- I put the correct SourceKite path for the `swift.path.sourcekite` key

However, when I open a swift file, the autocompletion doesn't work and I see this in the output pane:
```
Starting client failed
9
```

I'm not sure how to debug what's wrong. Any ideas please?

**Comment by akdor1154** [comment]
Need to change `engines` to vscode 1.26+, and update vscode-languageserver and vscode-languageclient to 5.x.

**Comment by vknabel** [comment]
Sorry for the late response. I currently have quite a lot to do.

@akdor1154 thank you very much! I updated the dependencies and released an update.

@VojtaStavik @akdor1154 can you confirm your issue has been fixed?

**Comment by VojtaStavik** [comment]
@vknabel Thank you very much for a for the quick fix! Everything seems to be OK 👍
