### ISSUE TITLE
Debugging tests

### ISSUE THREAD

**Issue by yeswolf** [vknabel/vscode-swift-development-environment#33]
We can debug tests in the following way:

1. Add 

```json
{
  "label": "tests",
  "type": "process",
  "command": "swift",
  "group": "build",
  "args": [
    "build",
    "--build-tests"
  ]
}
``` 
to ```tasks.json``` 

2. Configure the following task in ```launch.json```:

```json
{
  "type": "lldb",
  "request": "launch",
  "name": "Debug tests",
  "program": "<path to xctest executable>", //For example,  /Applications/Xcode.app/Contents/Developer/usr/bin/xctest
  "args": [
    "${workspaceFolder}.build/debug/<xctest bundle name>.xctest"
  ],
  "preLaunchTask": "tests"
}
```

Haven't tested it on Linux, but I think that only path to the xctest executable will be different.

**Comment by vknabel** [comment]
Thank you very much @yeswolf!

**Comment by vknabel** [comment]
Debugging UITests would be interesting (and I would be happy to link any solution for this), but I am sorry to say, that I do not know enough about debuggers and especially about debugging iOS apps.

Maybe the idea proposed in https://github.com/vadimcn/vscode-lldb/issues/95 may help? Alternatively one could find out how [ios-deploy](https://github.com/ios-control/ios-deploy) works internally and write a small bash script as a solution, if possible.

If you write some comments, could you link me? I'd like to keep up to date on this topic.
