### ISSUE TITLE
how are you supposed to install this extension on linux?

### ISSUE THREAD

**Issue by Luro02** [vknabel/vscode-swift-development-environment#35]
I already built the sourcekite dependency and I think it is working, (how do I test it?). I also set my path's according to the readme, ![screenshot of my settings.json](https://i.imgur.com/ozTAfFp.png)
```json
{
    "swift.path.swift_driver_bin": "/home/lucas/.swiftenv/versions/4.2-CONVERGENCE/usr/bin/swift",
    "swift.path.sourcekite": "/home/lucas/projects/swift/sourcekite/.build/release/sourcekite"
}
```
but I still don't have linting support. maybe someone can help me? I also attached the built sourcekite binary onto this issue. Thanks in advance :)
[sourcekite.zip](https://github.com/vknabel/vscode-swift-development-environment/files/2364167/sourcekite.zip)

**Comment by vknabel** [comment]
Thanks for your report.
If you have "Maintained Swift Development Environment" installed and it does not throw any errors when editing Swift files, it should be installed correctly. 

> but I still don't have linting support.

This extension mostly adds autocompletion. What exactly do you mean by linting? 
* SwiftLint (line-length, variable naming)? Requires a separate vscode extension.
* Compiler warnings/errors (syntax, types, deprecations) should be visible by red underlines.


If you want to test your sourcekite installation run

```bash
$ echo "1\n{\nkey.request: source.request.protocol_version\n}\n\n" | /home/lucas/projects/swift/sourcekite/.build/release/sourcekite
1
{
  key.version_major: 1,
  key.version_minor: 0
}


```

If you will receive an error instead of a valid response as shown above, the testing setup might help you: [vknabel/sourcekite/.travis.yml#L82](https://github.com/vknabel/sourcekite/blob/master/.travis.yml#L82).

**Comment by Luro02** [comment]
thanks for the response, my problem is, that I don't see any compiler errors under my code and I also don't have the recommended functions thing. The command above doesn't output anything at all! I built it with the commands, that travis uses.![](https://i.imgur.com/kfqE7LR.jpg)
I also built the debug version and it ouputs the following:
```
|||[main.swift:34] sourcekite - sourcekitd_initialize
|||[main.swift:42] sourcekite - state: endRequest
|||[main.swift:43] sourcekite - input: 1\n{\nkey.request: source.request.protocol_version\n}\n\n
|||[main.swift:44] sourcekite - input length: 57
|||[main.swift:48] sourcekite - wrong format for reqi
```

**Comment by vknabel** [comment]
Sorry for the wrong snippet. My ZSH replaced `\n` with newlines while bash doesn't.

The correct bash command would be:

```bash
$ echo "1
{
key.request: source.request.protocol_version
}

" | /home/lucas/projects/swift/sourcekite/.build/release/sourcekite
1
{
  key.version_major: 1,
  key.version_minor: 0
}

```

**Comment by Luro02** [comment]
the command above is working, so it is most likely related to the vscode installation itself, for example ctrl+shift+i outputs "there is no document formatter for swift files installed"

**Comment by vknabel** [comment]
That's weird. I never saw an error like this. Did you try a reinstall?

If it doesn't help, does manually setting `swift.path.shell` to your bash solve your problem?

**Comment by vknabel** [comment]
Thank you very much for your feedback!

The snippet you showed is not responsible for this issue. Type annotations in typescript are essentially just comments and have no runtime impact. Additionally the arguments are not used.

> I found that after creating a Workspace and putting my swift files in it, the extension would then load. 

Interesting! Glad to know that there is a workaround! I will have another try on that. 

> I have no idea if by design you are meant to need a workspace (I don't recall reading that you need to) but maybe it is a workaround for now?

In theory this should work the same for workspaces and simple folders. And on macOS it does.

**Comment by vknabel** [comment]
Were you using the debugger from this extension? If so you should better rely on LLDB Debugger as described in https://github.com/vknabel/vscode-swift-development-environment#debugging.

**Comment by mvdve** [comment]
Just to confirm, after adding my project folder to a workspace, the extension works. Otherwise i get an undefined error.
