### ISSUE TITLE
Report  Command failed: /usr/local/bin/swiftformat --fragment --indent 4error: --fragment option expects a value

### ISSUE THREAD

**Issue by l1Dan** [vknabel/vscode-swift-development-environment#38]
`Error: Command failed: /usr/local/bin/swiftformat --fragment --indent 4error: --fragment option expects a valueat checkExecSyncError (child_process.js:613:13)at Object.execFileSync (child_process.js:633:13)at Object.module.(anonymous function) [as execFileSync] (ELECTRON_ASAR.js:166:20)at format (/Users/lidan/.vscode/extensions/vknabel.vscode-swiftformat-1.1.1/out/src/SwiftFormatEditProvider.js:21:14)at SwiftFormatEditProvider.provideDocumentRangeFormattingEdits (/Users/lidan/.vscode/extensions/vknabel.vscode-swiftformat-1.1.1/out/src/SwiftFormatEditProvider.js:41:16)at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:503:427at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:108:368at new n.Class.derive._oncancel (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:85:776)at Object.t.asThenable (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:108:333)at e.provideDocumentRangeFormattingEdits (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:503:386)at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:516:908at e._withAdapter (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:512:91)at e.$provideDocumentRangeFormattingEdits (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:516:870)at t._doInvokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:640:888)at t._invokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:640:554)at t._receiveRequest (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:639:60)at t._receiveOneMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:638:59)at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:635:926at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:98:138at e.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:99:496)at a (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:154:213)at Socket._socketDataListener (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:154:432)at emitOne (events.js:116:13)at Socket.emit (events.js:211:7)at addChunk (_stream_readable.js:263:12)at readableAddChunk (_stream_readable.js:250:11)at Socket.Readable.push (_stream_readable.js:208:10)at Pipe.onread (net.js:594:20)`

**Comment by l1Dan** [comment]
format code error.

**Comment by vknabel** [comment]
@l1Dan thank you for your report! The new [1.1.2](https://github.com/vknabel/vscode-swiftformat/releases/tag/1.1.2) release should fix this issue.
