### ISSUE TITLE
When Apple’s VS Code extension has been released prompt to install it

### ISSUE THREAD

**Issue by vknabel** [vknabel/vscode-swift-development-environment#40]
Once the extension has been released to VS Code‘s extension registry and it is stable enough, we need to add a warning to prefer that instead if not installed yet. 

This should be an opt-out. 

More details: 
https://www.vknabel.com/pages/Apples-SourceKit-LSP-and-SDE-Roadmap/

**Comment by vknabel** [comment]
First step into this direction: as sourcekit-lsp is now included in Xcode by default, we switched the default LSP to it in [2.10.0](https://github.com/vknabel/vscode-swift-development-environment/releases/tag/2.10.0)

**Comment by tylerjames** [comment]
Does SourceKit work better in VSCode than it does in Xcode? I feel like it's pretty terrible in Xcode and I lose syntax highlighting all the time.

**Comment by vknabel** [comment]
@tylerjames all, Xcode, sourcekite and sourcekit-lsp rely on SourceKit and therefore share lots of the same problems. Especially for non-SwiftPM projects, using VS Code requires a greater initial effort and doesn't provide a few features Xcode can provide (running and debugging on iOS/on Simulators, refactorings, Swift Migrations, code coverage views, ...).

But the syntax highlighting in VS Code is more stable. 
So you can definitely give it a try and leave some feedback!

**Comment by vknabel** [comment]
As [announced on the forums] the swift server group has released an official [VS Code extension](https://forums.swift.org/t/introducing-swift-for-visual-studio-code/54246). So this phase of depreciation can start.
