### ISSUE TITLE
Support "Rename symbol" and other refactorings?

### ISSUE THREAD

**Issue by mattflix** [vknabel/vscode-swift-development-environment#46]
I am using version SDE 2.7.1.  Thanks for all your work supporting this.

I was just wondering if/when "Rename symbol" might be supported?

**Comment by vknabel** [comment]
Hey @mattflix! Thanks for the feedback. 

I agree that refactoring would be a great feature! Currently there are no explicit plans for this.
Though I will definitely have a look on this within the next few weeks.

**Comment by vknabel** [comment]
No plans to implement due to #40
