### ISSUE TITLE
Couldn't find a compatible version of Swift Development Environment with this version of Code.

### ISSUE THREAD

**Issue by rootscript** [vknabel/vscode-swift-development-environment#5]
Tried to install SDE 2.1.1 but found:
Error: Couldn't find a compatible version of Swift Development Environment with this version of Code.

I'm running macOS Sierra 10.12.6,
VSCode Version 1.10.2,
Swift version 4.0.3,
Apple Swift Package Manager - Swift 4.0.0-dev.

**Comment by vknabel** [comment]
@rootscript Thank you for your feedback.
This plugin requires at least Visual Studio Code `1.17.0`, the latest version is `1.19.1`.
Is there any particular reason why you still use `1.10.2`?

**Comment by rootscript** [comment]
@vknabel thanks for your quick reply. (I'm not sure why VSC 1.10.2 was even open on my machine, very strange)
I just tried SDE 2.1.2 with VSCode1.18.1 and install goes as planned.  Thanks again, for your quick reply.

**Comment by vknabel** [comment]
@rootscript that‘s great to hear. 
I already had the same bug with vscode. 
If you have any problems or questions, feel free to open an issue or contact me directly.
