### ISSUE TITLE
Unable to determine byte size

### ISSUE THREAD

**Issue by lokinfey** [vknabel/vscode-swift-development-environment#53]
Hi

    I need to debug swift code on linux , I set breakpoint in my code 
      
<img width="800" alt="Screen Shot 2019-08-09 at 8 56 37 PM" src="https://user-images.githubusercontent.com/4607663/62780420-37089880-bae8-11e9-91f1-4b44dc1e67bf.png">
  
    I want to go to check my variable value , but it shows some error:

<img width="556" alt="Screen Shot 2019-08-09 at 8 57 21 PM" src="https://user-images.githubusercontent.com/4607663/62780583-a1213d80-bae8-11e9-9205-d4170c0c9787.png">

   It shows  :

   Traceback (most recent call last):
  File "/home/xxx/.vscode-server-insiders/extensions/vadimcn.vscode-lldb-1.3.0/adapter2/codelldb.py", line 66, in evaluate_in_frame
    result = eval(script, eval_globals, eval_locals)
  File "<string>", line 1, in <module>
NameError: name 'fooBinary' is not defined

 
   What't the problem about that  in vs code debug watch tag ?

**Comment by vknabel** [comment]
Hi @lokinfey!
I wish I could help you. But the error you are experiencing is located in the [vadimcn/vscode-lldb](https://github.com/vadimcn/vscode-lldb) extension. Please open an issue there.

To help your issue being resolved fast, append relevant portions of your `launch.json` or even provide a repository containing all relevant code to reproduce the issue.

Feel free to open new issues here, if you have questions regarding Maintained SDE or the documentation within the repository!
