### ISSUE TITLE
Syntax / error checking and debugging problems.

### ISSUE THREAD

**Issue by ivaylopivanov** [vknabel/vscode-swift-development-environment#59]
Hello! Thanks for the extension! I'm trying it out now and having few problems. Seems like I managed to setup it, because I'm able to build and debug the app, however some features seem to be not working. Adding screenshots:

1) Syntax error is not highlighted
2) "Local variables" section is empty
![Screenshot 2019-11-16 at 10 10 14](https://user-images.githubusercontent.com/8849904/68990252-cea12400-0859-11ea-8090-87e5979c17e2.png)
![Screenshot 2019-11-16 at 10 09 58](https://user-images.githubusercontent.com/8849904/68990253-cea12400-0859-11ea-853d-18815cdbceba.png)

What did I miss to configure? Running this on Mojave 10.14.6 with swift 5.1 and using Sourcekite.

**Comment by vknabel** [comment]
Hi @ivaylopivanov! Thanks for your feedback!
I had a quick look regarding the syntax and type errors. This is a bug. It might take a bit to fix, but I will definitely work on this. 👍

Regarding the empty local variables within the debugger: please open a new issue at https://github.com/vadimcn/vscode-lldb and attach your debugging configuration.

**Comment by vknabel** [comment]
The latest release should fix the syntax errors! See [CHANGELOG.md#282](https://github.com/vknabel/vscode-swift-development-environment/blob/master/CHANGELOG.md#282)
