### ISSUE TITLE
what's the difference between this one and jinmingjian/sde

### ISSUE THREAD

**Issue by strangemonad** [vknabel/vscode-swift-development-environment#6]
There's obvious similar project history but no clear indication. Has development continued here? Is this a fork?

**Comment by vknabel** [comment]
@strangemonad jinmingjian/sde has been discontinued and does not support swift 4. und  This fork does support it and I do my best to keep this project alive. See https://github.com/jinmingjian/sde/pull/40

**Comment by afturner** [comment]
You should really ask jinmingjian to edit his repo or remove it to reflect this. I suggest doing the same with your README cause it's kinda confusing

**Comment by vknabel** [comment]
@afturner thank you for your feedback. I will open a PR soon.

**Comment by LinusU** [comment]
Yeah, this took me quite some time to figure out 😄 

Would be awesome to update the readme 👍

**Comment by vknabel** [comment]
I did update the readme and the title to make it more clear, which extension is currently maintained until the original project will be modified.

**Comment by vknabel** [comment]
I guess I can close this issue. There isn't anything we could do now.
