### ISSUE TITLE
sourcekit-lsp returns some errors

### ISSUE THREAD

**Issue by haifengkao** [vknabel/vscode-swift-development-environment#63]
`sourcekit-lsp` returns some errors 
![截圖 2020-03-06 上午12 48 03](https://user-images.githubusercontent.com/4080524/76004272-2f0cbc00-5f44-11ea-85b9-f51d2b4d5f38.jpg)

**Step to reproduce:**
1. install the latest sourcekit-lsp by installing Xcode 11.4 beta
https://github.com/apple/sourcekit-lsp/tree/master/Editors
2. add the following  settings to `vscode-swift-development-environment`
`Sde: Language Server Mode`: sourcekit-lsp
`Sourcekit-lsp: Server Path`:
 /Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/sourcekit-lsp
`Sourcekit-lsp: Toolchain Path`
/Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain
3. create an initial project by
`mkdir helloworld`
` cd helloworld` 
` swift package init`
4. open the project by vscode

IMO, the vscode extension provided by `sourcekit-lsp` is working perfectly. But it lacks certain features like auto-build when the project is saved. 
If SDE can continue to support `sourcekit-lsp`, it will be the best solution at this moment.

**Comment by vknabel** [comment]
Hi @haifengkao! Thanks for the report. I will definitely have a look on this!

**Comment by vknabel** [comment]
Good news, @haifengkao! The release [2.9.0](https://github.com/vknabel/vscode-swift-development-environment/tree/2.9.0) fixes your issue.

The environment variables haven't been passed correctly to `sourcekit-lsp`.
