### ISSUE TITLE
the completion is very slow 

### ISSUE THREAD

**Issue by haifengkao** [vknabel/vscode-swift-development-environment#68]
When I specified the build params with `sourcekit-lsp` backend,

```
"sde.swiftBuildingParams" : [
        "build",
        "-Xswiftc",
        "-sdk",
        "-Xswiftc",
        "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk",
        "-Xswiftc",
        "-target",
        "-Xswiftc",
        "arm64-apple-ios11.0"
    ]
```
the completion becomes very slow. I have to wait for 2~3 secs for the completion menu to popup 

The problem comes from `sourcekit-lsp` itself. 
https://forums.swift.org/t/sourcekit-lsp-completion-delay-with-sublime-text/30655
`sourcekit-lsp` will dump all global variables in the SDK to a  json file without filtering. 

The` sourcekit-lsp` team is working on this issue.
https://github.com/apple/sourcekit-lsp/commits/master

After they are finished (if [vscode-lsp](https://github.com/microsoft/vscode-languageserver-node) supports it), the problem might be resolved.

**Comment by vknabel** [comment]
Thanks for the details!

**Comment by haifengkao** [comment]
I have implemented the server-side filtering
The OS X binary and source codes can be find here 
https://github.com/haifengkao/fast-sourcekit-lsp/releases

**Comment by vknabel** [comment]
@haifengkao thanks for your work! Might try out your fork!

**Comment by vknabel** [comment]
As this is can only be fixed in `sourcekit-lsp` and as there is a workaround with https://github.com/haifengkao/fast-sourcekit-lsp/releases, I will close this issue.
