### ISSUE TITLE
missing dependant sourcekite tool, please configure correct "swift.path.sourcekite"

### ISSUE THREAD

**Issue by vknabel** [vknabel/vscode-swift-development-environment#7]
*Previously reported by @JustinMoser in https://github.com/jinmingjian/sde/issues/43*

Hi,
I am unable to use this extension. I am running VS Code on macOS High Sierra, and i get the above error message. This is the output:

```
justinmoser/.vscode/extensions/vknabel.vscode-swift-development-environment-2.1.2/out/src/server/sourcekites.js:43
        throw err;
        ^

Error: spawn swift build -Xswiftc -framework -Xswiftc sourcekitd -Xswiftc -F -Xswiftc /Library/Developer/Toolchains/swift-latest.xctoolchain/usr/lib -Xlinker -rpath -Xlinker /Library/Developer/Toolchains/swift-latest.xctoolchain/usr/lib ENOENT
    at exports._errnoException (util.js:1050:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
[Error - 18:10:48] Connection to server got closed. Server will not be restarted.
```

I have run the build / link command as instructed on the sourcekite repo page. From my root directory (HD root):

`> git clone https://github.com/jinmingjian/sourcekite.git`
`> cd sourcekite`
`> swift build -Xswiftc -framework -Xswiftc sourcekitd -Xswiftc -F -Xswiftc /Library/Developer/Toolchains/swift-latest.xctoolchain/usr/lib -Xlinker -rpath -Xlinker /Library/Developer/Toolchains/swift-latest.xctoolchain/usr/lib`

and then added this to my settings.json file, under the user settings tab:

`"swift.path.sourcekite": "/Users/justinmoser/sourcekite/.build/debug/sourcekite"`

I also get the message:

`Incorrect type. Expected "array".`

in the launch.json file on this key:

`"configurations": "sde.commands.debug.provideInitialConfigurations"`

**Comment by vknabel** [comment]
@JustinMoser I did move your issue. Thanks for trying this out.

1. Regarding `Incorrect type. Expected "array".`:
`configurations` can include multiple test targets and therefore requires an array. You provided a string. The `launch.json` should contain something similar to

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "swift-debug",
            "request": "launch",
            "name": "Swift Program Debug",
            "program": "${workspaceRoot}/.build/debug/path-to-program-debugged"
        }
    ]
}
```

2. Regarding `please configure correct "swift.path.sourcekite"`:

> I have run the build / link command as instructed on the sourcekite repo page. From my root directory (HD root):

> `"swift.path.sourcekite": "/Users/justinmoser/sourcekite/.build/debug/sourcekite"`

If I understand you correctly, your working directory has been `/`, not `/Users/justinmoser`. But your configured path has been `/Users/justinmoser/sourcekite/.build/debug/sourcekite` instead of the actual location of `/sourcekite/.build/debug/sourcekite`.
If I am right, you either need to change your config `"swift.path.sourcekite": "/sourcekite/.build/debug/sourcekite"` or move the cloned repo `mv -f /sourcekite ~/sourcekite`.


Did this solve your problem?

**Comment by JustinMoser** [comment]
Hi!
Thanks so much for your reply, no my sourcekite clone is in ~/sourcekite currently. I changed the entry in my user settings to `"swift.path.sourcekite": "~/sourcekite/.build/debug/sourcekite"` however I am still receiving the same error above (regarding configuring a correct sourcekite).

The output has now changed to:

```
/Users/justinmoser/.vscode/extensions/vknabel.vscode-swift-development-environment-2.1.2/out/src/server/sourcekites.js:43
        throw err;
        ^

Error: spawn ~/sourcekite/.build/debug/sourcekite ENOENT
    at exports._errnoException (util.js:1050:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
[Info  - 13:27:38] Connection to server got closed. Server will restart.
/Users/justinmoser/.vscode/extensions/vknabel.vscode-swift-development-environment-2.1.2/out/src/server/sourcekites.js:43
        throw err;
        ^

Error: spawn ~/sourcekite/.build/debug/sourcekite ENOENT
    at exports._errnoException (util.js:1050:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
[Info  - 13:27:39] Connection to server got closed. Server will restart.
/Users/justinmoser/.vscode/extensions/vknabel.vscode-swift-development-environment-2.1.2/out/src/server/sourcekites.js:43
        throw err;
        ^

Error: spawn ~/sourcekite/.build/debug/sourcekite ENOENT
    at exports._errnoException (util.js:1050:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
[Info  - 13:27:39] Connection to server got closed. Server will restart.
/Users/justinmoser/.vscode/extensions/vknabel.vscode-swift-development-environment-2.1.2/out/src/server/sourcekites.js:43
        throw err;
        ^

Error: spawn ~/sourcekite/.build/debug/sourcekite ENOENT
    at exports._errnoException (util.js:1050:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
[Error - 13:27:39] Connection to server got closed. Server will not be restarted.

```

Thank you!

**Comment by vknabel** [comment]
@JustinMoser your absolute path with `/Users/justinmoser/sourcekite/.build/debug/sourcekite` has been correct. The expansion of `~` to `/Users/justinmoser` does not work within this setting.

Sometimes you may need to close and reopen your vscode window after editing the settings to restart the extension. Maybe that's the problem?
If you paste `which /Users/justinmoser/sourcekite/.build/debug/sourcekite` into your terminal: does it find the binary?

**Comment by JustinMoser** [comment]
@vknabel thank you so much this seems to have fixed my issues! :)

**Comment by vknabel** [comment]
@JustinMoser great to hear!

**Comment by JustinMoser** [comment]
@vknabel apologies! It actually hasnt....

It says build succeeded at the bottom of VSC but im still getting the error regarding the configuring a correct sourcekite. (with the output above!)

I also get the following error:

`The Swift server crashed 5 times in the last 3 minutes. The server will not be restarted.`

Sorry about this!

**Comment by JustinMoser** [comment]
@vknabel Ah! it was because I changed the sourcekite path back to the relative path with the ~/sourcekite path instead. When I use the absolute path it works fine.

Also - for the debug configuration, the end path of in your example is "path-to-program-debugged" and in the root of .build/debug/ there is a test_swift_project file, so I have set the key as:

`"program": "${workspaceRoot}/.build/debug/swift_test_project"`

however when I start debugging, nothing seems to happen. The first line of my main.swift is:

`print("Hello, world!")`

so it should be printing to the output window correct?

Thanks again.

**Comment by vknabel** [comment]
@JustinMoser does the debugging start or will it always display a loading indicator?
What happens if you add a breakpoint for `print("Hello, world!")`?

**Comment by vknabel** [comment]
@JustinMoser as I found out (thanks @renanyoy) the best possibility for debugging Swift probably is [LLDB Debugger](https://marketplace.visualstudio.com/items?itemName=vadimcn.vscode-lldb).

Below an example configuration. I also included a `preLaunchTask` which will compile your project.
```js
// launch.json
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "lldb",
            "request": "launch",
            "name": "Archery",
            "program": "${workspaceFolder}/.build/debug/archery",
            "args": [],
            "cwd": "${workspaceFolder}",
            "preLaunchTask": "swift-build"
        }
}
```

```js
// tasks.json
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "swift-build",
            "type": "shell",
            "command": "swift build"
        }
}
```
