### ISSUE TITLE
How to Show Variables in  VSCode

### ISSUE THREAD

**Issue by lokinfey** [vknabel/vscode-swift-development-environment#76]
hi
   I use CodeLLDB to finish sourcekit-lsp debug in window wsl 2 / ubuntu linux

   But it can not show local variables in  VSCode :

   
   ![Screenshot (1)](https://user-images.githubusercontent.com/4607663/87853360-d6125300-c93b-11ea-9c0f-979cee80edf5.png)

   How to set some to see my local variable

**Comment by haifengkao** [comment]
I don't use CodeLLDB, sorry :(

**Comment by lokinfey** [comment]
> I don't use CodeLLDB, sorry :(

But How you set debug swift in Ubuntu .....?  Can you help me

**Comment by vknabel** [comment]
Hi @lokinfey.

I am sorry to say, I currently don't have enough free space left on my mac to install an Ubuntu VM with Swift (or even a Windows).
Nonetheless please head to the [vscode-lldb extensions repository](https://github.com/vadimcn/vscode-lldb) in case you have problems with it. This project is not related to the lldb debugger.

To get valuable feedback there, provide as much information as possible (your system and vscode configurations, the Swift version, an open source project where you could reproduce your issue, feel free to link this issue and me, etc).

Explicitly regarding your screenshot:
The local `i`-variable might have been optimized out by the Swift compiler, as it was never used.
Does `return "It works: \(i)"` fix your issue?
Do Static or Global variables work?

I hope this helps!
