### ISSUE TITLE
Links in the README.md are broken/not updated

### ISSUE THREAD

**Issue by avinal** [vknabel/vscode-swift-development-environment#83]
For example issue link below this header
https://github.com/vknabel/vscode-swift-development-environment/blob/master/README.md#other-questions

**Comment by vknabel** [comment]
Thanks a lot @avinal! Could you find another broken link?

**Comment by avinal** [comment]
Yeah I had a few yesterday, I forgot them 😅, I will see again and let you know.👍

**Comment by avinal** [comment]
I think there are no more, I checked, it might be some problem in VS Code.
