### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by clayreimann** [vknabel/vscode-swift-development-environment#88]
We should add tests to the project. 

[VSCode extension testing guide](https://code.visualstudio.com/api/working-with-extensions/testing-extension)

**Comment by vknabel** [comment]
Yes we should. Not sure where to start though. Would it be best to start with https://github.com/vknabel/vscode-swiftlint or https://github.com/vknabel/vscode-swiftformat as they are much simpler?
And then scaling up to this project?
