### ISSUE TITLE
Run default target doesn't work

### ISSUE THREAD

**Issue by congnd** [vknabel/vscode-swift-development-environment#94]
Thanks for such a great tool!

I'm want to use the `Run Default Target` command to quickly run the program but it doesn't seem to work as expected.
From what I can see in the output, it seems that there was no target was sent to the `swift run` command.

```
running package…
pid: 862 - /usr/bin/swift run 
error: no executable product named ''
Process exited. code=1 signal=null
```

**Comment by vknabel** [comment]
Hey @congnd! Thanks for the kind words!

Could you paste your Package.swift-file (better: or link an open source repo)?
We try to have a look on this soon. 👍

**Comment by congnd** [comment]
hey @vknabel 
there you go: https://github.com/congnd/FMPhotoPicker

Thanks for your rapid response.

**Comment by vknabel** [comment]
Hey @congnd!

The latest [2.11.2](https://github.com/vknabel/vscode-swift-development-environment/releases/tag/2.11.2) release now fixes your problem. Though as your linked repository does not contain any executables, it will still fail, but with a different error:

```
running package…
pid: 17701 - /usr/bin/swift run
error: no executable product available
Process exited. code=1 signal=null

```
