### ISSUE TITLE
Support for creating a standalone package

### ISSUE THREAD

**Issue by wmorgue** [vknabel/vscode-swift-development-environment#95]
Hello 👋🏻

Can someone implement support for creating packages with a different type, like library or executable?

Some of the ideas:
1. Ask a package name.
2. Ask a package type.

```
swift package init --type empty
swift package init --type executable
swift package init --type library
```
3. Create package with input name and selected type.

**Comment by vknabel** [comment]
Hi @wmorgue!

I didn't try, but it seems like this extension already implements your requested features: https://github.com/cgrevisse/swift-project-creation
