### ISSUE TITLE
Add option to never show output tab

### ISSUE THREAD

**Issue by j-f1** [vknabel/vscode-swift-development-environment#99]
Currently, if the build fails, the output tab is forcibly opened (due to this line of code)

https://github.com/vknabel/vscode-swift-development-environment/blob/843706ba246b60ffb6b8bc7dd221ed778aa9df36/src/toolchain/SwiftTools.ts#L139

Since the Problems tab displays much richer output, it would be great to have an option to never show the raw output (or perhaps only display raw output if parsing the list of problems out failed, indicating a more catastrophic issue).

**Comment by vknabel** [comment]
Not sure when I have enough time to tackle this. PRs welcome.
